name: Dev Deploy

on:
  push:
    branches: [ '*' ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_KEY }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        builder: ${{ steps.buildx.outputs.name }}
        repository: slatedocs/slate
        platforms: linux/amd64,linux/arm64,linux/ppc64le
        tag_with_ref: true
